project_id = "npqujpfqsnwxowlciyof"

[functions.contract-signature-public]
verify_jwt = false

[functions.receive-reseller-registration]
verify_jwt = false

[functions.reseller-consultants]
verify_jwt = false
