// Receives new registrations from the external "Revenda MCI" landing page.
// Security & reliability:
//  - POST only, Origin allowlist (no wildcard).
//  - Persistent DB-backed rate limit (5/min per hashed IP), shared across instances.
//  - Honeypot + minimum form fill time.
//  - Payload validated with zod (unknown fields are stripped, never persisted as columns).
//  - Idempotency by external_registration_id (UUID generated by the landing page).
//  - CNPJ/e-mail/phone/CEP normalized. CNPJ validated by check digit.
//  - Duplicate detection by CNPJ -> email -> phone. Never overwrites an existing portfolio.
//  - service_role is used only server-side.
import { createClient } from 'npm:@supabase/supabase-js@2';
import { z } from 'npm:zod@3.23.8';

const DEFAULT_ORIGINS = [
  'https://cadastro-revenda-mci.lovable.app',
  'https://cadastro-revenda.mcicrm.online',
];
const ALLOWED_ORIGINS = (() => {
  const fromEnv = (Deno.env.get('RESELLER_LANDING_ORIGINS') ?? '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
  return fromEnv.length ? fromEnv : DEFAULT_ORIGINS;
})();

const MIN_FILL_MS = 3000;

function corsFor(origin: string | null): Record<string, string> {
  const allow = origin && ALLOWED_ORIGINS.includes(origin) ? origin : '';
  return {
    'Access-Control-Allow-Origin': allow,
    'Access-Control-Allow-Headers': 'content-type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Max-Age': '86400',
    'Vary': 'Origin',
  };
}

// --- Normalizers ---
const digits = (s: string) => (s ?? '').replace(/\D/g, '');
const normEmail = (s: string) => (s ?? '').trim().toLowerCase();

function validCnpj(raw: string): boolean {
  const c = digits(raw);
  if (c.length !== 14 || /^(\d)\1{13}$/.test(c)) return false;
  const calc = (base: string, weights: number[]) => {
    const sum = base.split('').reduce((a, d, i) => a + Number(d) * weights[i], 0);
    const m = sum % 11;
    return m < 2 ? 0 : 11 - m;
  };
  const w1 = [5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2];
  const w2 = [6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2];
  const d1 = calc(c.slice(0, 12), w1);
  const d2 = calc(c.slice(0, 12) + d1, w2);
  return c.endsWith(`${d1}${d2}`);
}

// --- Schema (unknown keys are stripped by zod's default object behaviour) ---
const Payload = z.object({
  external_registration_id: z.string().uuid(),
  responsible_name: z.string().trim().min(2).max(200),
  company_name: z.string().trim().min(2).max(255),
  trade_name: z.string().trim().max(255).optional().nullable(),
  cnpj: z.string().min(11).max(20),
  state_registration: z.string().trim().max(30).optional().nullable(),
  cep: z.string().max(20).optional().nullable(),
  city: z.string().trim().max(120).optional().nullable(),
  street: z.string().trim().max(255).optional().nullable(),
  state: z.string().trim().max(2).optional().nullable(),
  neighborhood: z.string().trim().max(120).optional().nullable(),
  address_number: z.string().trim().max(20).optional().nullable(),
  complement: z.string().trim().max(120).optional().nullable(),
  website: z.string().trim().max(255).optional().nullable(),
  years_in_market: z.string().trim().max(40).optional().nullable(),
  email: z.string().email().max(255),
  phone: z.string().min(8).max(30),
  how_did_you_know: z.string().trim().max(255).optional().nullable(),
  consultant_code: z.string().trim().max(80).optional().nullable(),
  interests: z.array(z.string().max(120)).max(30).optional().default([]),
  message: z.string().trim().max(5000).optional().nullable(),
  privacy_consent: z.boolean(),
  commercial_contact_consent: z.boolean().optional().default(false),
  form_url: z.string().max(500).optional().nullable(),
  referrer: z.string().max(500).optional().nullable(),
  utm_source: z.string().max(120).optional().nullable(),
  utm_medium: z.string().max(120).optional().nullable(),
  utm_campaign: z.string().max(120).optional().nullable(),
  utm_content: z.string().max(120).optional().nullable(),
  utm_term: z.string().max(120).optional().nullable(),
  submitted_at: z.string().datetime().optional().nullable(),
  honeypot: z.string().max(200).optional().nullable(),
  form_started_at: z.string().datetime().optional().nullable(),
});

async function sha256(s: string) {
  const buf = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(s));
  return Array.from(new Uint8Array(buf)).map((b) => b.toString(16).padStart(2, '0')).join('');
}

Deno.serve(async (req) => {
  const origin = req.headers.get('origin');
  const cors = corsFor(origin);
  const json = (body: unknown, status = 200) =>
    new Response(JSON.stringify(body), { status, headers: { ...cors, 'Content-Type': 'application/json' } });

  if (req.method === 'OPTIONS') return new Response('ok', { headers: cors });
  if (req.method !== 'POST') return json({ error: 'method_not_allowed' }, 405);

  if (!origin || !ALLOWED_ORIGINS.includes(origin)) return json({ error: 'origin_not_allowed' }, 403);

  const supabase = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
  );

  const ip = req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() || 'unknown';
  const ipHash = await sha256(ip);

  // Persistent rate limit (shared across function instances). Never logs the payload.
  const { data: blocked, error: rlErr } = await supabase.rpc('reseller_rate_limit_hit', {
    p_ip_hash: ipHash,
    p_max: 5,
    p_window_seconds: 60,
  });
  if (rlErr) console.error('rate_limit_check_failed', rlErr.message);
  if (blocked === true) return json({ error: 'rate_limited' }, 429);

  // Parse and validate
  let raw: unknown;
  try {
    raw = await req.json();
  } catch {
    return json({ error: 'invalid_json' }, 400);
  }
  const parsed = Payload.safeParse(raw);
  if (!parsed.success) {
    return json({ error: 'validation_failed', details: parsed.error.flatten().fieldErrors }, 400);
  }
  const body = parsed.data;

  // Anti-spam: honeypot must be empty, and the form must take a minimum time to fill.
  if (body.honeypot && body.honeypot.trim() !== '') return json({ error: 'spam_detected' }, 400);
  if (body.form_started_at) {
    const elapsed = Date.now() - new Date(body.form_started_at).getTime();
    if (elapsed >= 0 && elapsed < MIN_FILL_MS) return json({ error: 'form_too_fast' }, 400);
  }

  // Normalize
  const cnpj = digits(body.cnpj);
  const email = normEmail(body.email);
  const phone = digits(body.phone);
  const cep = digits(body.cep ?? '');

  if (!validCnpj(cnpj)) return json({ error: 'invalid_cnpj' }, 400);
  if (!body.privacy_consent) return json({ error: 'privacy_consent_required' }, 400);

  // --- IDEMPOTENCY: same external_registration_id returns the previous result ---
  const { data: existingReg } = await supabase
    .from('reseller_registrations')
    .select('id, client_id, is_duplicate, duplicate_reason, assignment_reason, registration_status')
    .eq('external_registration_id', body.external_registration_id)
    .maybeSingle();
  if (existingReg) {
    return json({
      ok: true,
      idempotent: true,
      registration_id: existingReg.id,
      client_id: existingReg.client_id,
      duplicate: existingReg.is_duplicate,
      duplicate_reason: existingReg.duplicate_reason,
      assignment_reason: existingReg.assignment_reason,
      status: existingReg.registration_status,
    });
  }

  // Resolve consultant selection
  const selectedCode = (body.consultant_code ?? '').trim().toLowerCase();
  let assignmentReason: string;
  let assignedUserId: string | null = null;
  let selectedLabel: string | null = null;
  const selectedCodeStored: string | null = selectedCode || null;

  const { data: consultantRow } = selectedCode
    ? await supabase
        .from('reseller_consultants')
        .select('consultant_code, display_name, crm_user_id, is_none_option, active')
        .eq('consultant_code', selectedCode)
        .maybeSingle()
    : { data: null } as const;

  if (!selectedCode) {
    assignmentReason = 'missing_selection';
  } else if (!consultantRow) {
    assignmentReason = 'invalid_consultant';
  } else if (!consultantRow.active) {
    selectedLabel = consultantRow.display_name;
    assignmentReason = 'inactive_consultant';
  } else if (consultantRow.is_none_option) {
    selectedLabel = consultantRow.display_name;
    assignmentReason = 'default_none';
  } else {
    selectedLabel = consultantRow.display_name;
    assignedUserId = consultantRow.crm_user_id;
    assignmentReason = 'consultant_selected';
  }

  // Duplicate detection (CNPJ -> email -> phone)
  let dupClient:
    | { id: string; salesperson_id: string | null; assigned_user_id: string | null }
    | null = null;
  let dupReason: string | null = null;
  for (const [field, value] of [
    ['cpf_cnpj', cnpj],
    ['email', email],
    ['phone', phone],
  ] as const) {
    if (!value) continue;
    const { data } = await supabase
      .from('clients')
      .select('id, salesperson_id, assigned_user_id')
      .eq(field, value)
      .limit(1)
      .maybeSingle();
    if (data) {
      dupClient = data;
      dupReason = field;
      break;
    }
  }

  // Existing client keeps its current owner. The follow-up goes to that owner.
  const consultantChoiceHonoured = !dupClient || !(dupClient.assigned_user_id || dupClient.salesperson_id);
  if (dupClient) {
    const currentOwner = dupClient.assigned_user_id ?? dupClient.salesperson_id ?? null;
    if (currentOwner) {
      assignedUserId = currentOwner;
      assignmentReason = 'existing_client_owner';
    }
  }

  // Fallback to the default consultant when there is still no assignment
  if (!assignedUserId) {
    const { data: fallback } = await supabase
      .from('reseller_consultants')
      .select('crm_user_id')
      .eq('is_default_fallback', true)
      .eq('active', true)
      .maybeSingle();
    if (fallback?.crm_user_id) {
      assignedUserId = fallback.crm_user_id;
      assignmentReason = assignmentReason === 'consultant_selected' ? assignmentReason : 'default_fallback';
    } else {
      assignmentReason = 'pending_distribution';
    }
  }

  const nowIso = new Date().toISOString();
  const status = assignmentReason === 'pending_distribution' ? 'pendente_distribuicao' : 'novo';

  // Create the client only when there is no duplicate. Never overwrite an existing client.
  let clientId: string | null = dupClient?.id ?? null;
  if (!dupClient) {
    const { data: newClient, error: insErr } = await supabase
      .from('clients')
      .insert({
        name: body.responsible_name,
        company_name: body.company_name,
        contact_name: body.responsible_name,
        cpf_cnpj: cnpj,
        email,
        phone,
        contact_phone: phone,
        cep,
        city: body.city,
        state: body.state,
        address: body.street,
        address_number: body.address_number,
        neighborhood: body.neighborhood,
        complement: body.complement,
        pipeline_stage: 'lead',
        is_revenda: true,
        // created_by is the official CRM ownership/wallet field (RLS + "Meus clientes").
        created_by: assignedUserId,
        salesperson_id: assignedUserId,
        assigned_user_id: assignedUserId,
        assigned_at: assignedUserId ? nowIso : null,
        received_at: nowIso,
        is_new_registration: true,
        source: 'landing_revenda_mci',
        source_label: 'Landing Page — Revenda MCI',
        registration_status: status,
        external_registration_id: body.external_registration_id,
        notes: body.message ?? null,
      })
      .select('id')
      .single();
    if (insErr) {
      console.error('client_insert_failed', insErr.message);
      return json({ error: 'client_insert_failed' }, 500);
    }
    clientId = newClient.id;
  }

  // Always store the raw registration.
  const { data: reg, error: regErr } = await supabase
    .from('reseller_registrations')
    .insert({
      external_registration_id: body.external_registration_id,
      client_id: clientId,
      is_duplicate: !!dupClient,
      duplicate_reason: dupReason,
      registration_status: status,
      responsible_name: body.responsible_name,
      company_name: body.company_name,
      trade_name: body.trade_name,
      cnpj,
      state_registration: body.state_registration,
      cep,
      city: body.city,
      street: body.street,
      state: body.state,
      neighborhood: body.neighborhood,
      address_number: body.address_number,
      complement: body.complement,
      website: body.website,
      years_in_market: body.years_in_market,
      email,
      phone,
      how_did_you_know: body.how_did_you_know,
      interests: body.interests ?? [],
      message: body.message,
      privacy_consent: body.privacy_consent,
      commercial_contact_consent: body.commercial_contact_consent ?? false,
      consultant_selected_code: selectedCodeStored,
      consultant_selected_label: selectedLabel,
      assigned_user_id: assignedUserId,
      assignment_reason: assignmentReason,
      submitted_at: body.submitted_at ?? nowIso,
      form_started_at: body.form_started_at ?? null,
      form_url: body.form_url,
      referrer: body.referrer,
      origin,
      utm_source: body.utm_source,
      utm_medium: body.utm_medium,
      utm_campaign: body.utm_campaign,
      utm_content: body.utm_content,
      utm_term: body.utm_term,
      ip_hash: ipHash,
      raw_payload: body,
    })
    .select('id')
    .single();
  if (regErr) {
    // Unique violation => concurrent retry with the same external id: return the stored one.
    if ((regErr as { code?: string }).code === '23505') {
      const { data: again } = await supabase
        .from('reseller_registrations')
        .select('id, client_id, is_duplicate, duplicate_reason, assignment_reason, registration_status')
        .eq('external_registration_id', body.external_registration_id)
        .maybeSingle();
      if (again) {
        return json({
          ok: true,
          idempotent: true,
          registration_id: again.id,
          client_id: again.client_id,
          duplicate: again.is_duplicate,
          duplicate_reason: again.duplicate_reason,
          assignment_reason: again.assignment_reason,
          status: again.registration_status,
        });
      }
    }
    console.error('registration_insert_failed', regErr.message);
    return json({ error: 'registration_insert_failed' }, 500);
  }

  if (!dupClient && clientId) {
    await supabase.from('clients').update({ external_registration_id: body.external_registration_id }).eq('id', clientId);
  }

  // --- History (append-only, no sensitive form data duplicated) ---
  const history: Record<string, unknown>[] = [{
    registration_id: reg.id,
    action: 'received',
    new_status: status,
    new_assigned_user_id: assignedUserId,
    metadata: { origin, consultant_selected_code: selectedCodeStored },
  }];
  if (dupClient) {
    history.push({
      registration_id: reg.id,
      action: 'duplicate_detected',
      new_status: status,
      metadata: { duplicate_reason: dupReason, client_id: clientId },
    });
  }
  if (assignedUserId) {
    history.push({
      registration_id: reg.id,
      action: 'assigned',
      new_assigned_user_id: assignedUserId,
      metadata: { assignment_reason: assignmentReason, client_id: clientId },
    });
  } else {
    history.push({
      registration_id: reg.id,
      action: 'pending_distribution',
      new_status: status,
      metadata: { assignment_reason: assignmentReason, client_id: clientId },
    });
  }
  await supabase.from('reseller_registration_history').insert(history);

  // Bump consultant received_count only when the chosen consultant actually got the lead.
  if (assignmentReason === 'consultant_selected' && selectedCodeStored) {
    const { data: c } = await supabase
      .from('reseller_consultants')
      .select('id, received_count')
      .eq('consultant_code', selectedCodeStored)
      .maybeSingle();
    if (c) {
      await supabase
        .from('reseller_consultants')
        .update({ received_count: (c.received_count ?? 0) + 1 })
        .eq('id', c.id);
    }
  }

  // --- Notifications: only the effective owner (never the unchosen consultant) ---
  const notify = async (userId: string, title: string, message: string, type: string) => {
    const { error } = await supabase.from('notifications').insert({
      user_id: userId,
      title,
      message,
      type,
      related_client_id: clientId,
    });
    await supabase.from('reseller_registration_history').insert({
      registration_id: reg.id,
      action: error ? 'notification_failed' : 'notification_created',
      new_assigned_user_id: userId,
      metadata: { type, error: error?.message ?? null },
    });
  };

  if (assignedUserId) {
    await notify(
      assignedUserId,
      dupClient ? 'Nova solicitação de revenda (cliente existente)' : 'Novo cadastro de revenda recebido',
      dupClient
        ? `${body.company_name} enviou uma nova solicitação pela Landing Revenda MCI. O cliente já está na sua carteira.`
        : `Novo cadastro de revenda recebido: ${body.company_name}. O cliente foi adicionado à sua carteira.`,
      'reseller_registration',
    );
  } else {
    const { data: admins } = await supabase.from('user_roles').select('user_id').eq('role', 'admin');
    for (const a of admins ?? []) {
      await notify(
        a.user_id,
        'Cadastro pendente de distribuição',
        `Um cadastro da Landing Revenda MCI (${body.company_name}) não pôde ser atribuído automaticamente e aguarda distribuição.`,
        'reseller_registration_pending',
      );
    }
  }

  return json({
    ok: true,
    idempotent: false,
    registration_id: reg.id,
    client_id: clientId,
    duplicate: !!dupClient,
    duplicate_reason: dupReason,
    assignment_reason: assignmentReason,
    consultant_choice_honoured: consultantChoiceHonoured,
    status,
  });
});
