// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-clients.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/_bridge.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";

// supabase/functions/_shared/crm-handlers.ts
var APPROVED_STATUSES = ["approved", "aprovado", "aprovada", "won", "closed_won"];
var okEnv = (entity, extra = {}) => ({
  ok: true,
  entity,
  ...extra
});
var errEnv = (entity, error) => ({ ok: false, entity, error });
function scopeCompany(query, ctx) {
  if (ctx.companyId) {
    return query.eq("company_id", ctx.companyId);
  }
  return query;
}
function scopeOwn(query, column, ctx, scope) {
  query = scopeCompany(query, ctx);
  const role = ctx.profile?.role;
  const isBoss = role === "admin" || role === "gestor";
  if (isBoss && scope === "team") return query;
  return query.eq(column, ctx.userId);
}
async function listClients(ctx, args = {}) {
  const limit = Math.min(args.limit ?? 25, 200);
  let q = ctx.supabase.from("clients").select("id,name,company_name,email,phone,city,state,salesperson_id,created_by,last_interaction_at,created_at").order("company_name", { ascending: true }).limit(limit);
  q = scopeOwn(q, "salesperson_id", ctx, args.scope);
  if (args.search) {
    const like = `%${args.search}%`;
    q = q.or(`name.ilike.${like},company_name.ilike.${like},email.ilike.${like},phone.ilike.${like}`);
  }
  const { data, error } = await q;
  if (error) return errEnv("clients", error.message);
  return okEnv("clients", {
    columns: ["company_name", "name", "city", "state", "email", "phone"],
    rows: data ?? [],
    count: data?.length ?? 0
  });
}
async function searchClients(ctx, args) {
  const limit = Math.min(args.limit ?? 20, 50);
  const like = `%${args.query}%`;
  let q = ctx.supabase.from("clients").select("id,name,company_name,email,phone,city,state,cpf_cnpj,created_at").limit(limit);
  q = scopeOwn(q, "salesperson_id", ctx);
  q = q.or(`name.ilike.${like},company_name.ilike.${like},email.ilike.${like},phone.ilike.${like},city.ilike.${like},cpf_cnpj.ilike.${like}`);
  const { data, error } = await q;
  if (error) return errEnv("clients", error.message);
  return okEnv("clients", { rows: data ?? [], count: data?.length ?? 0 });
}
async function getCustomerHistory(ctx, args) {
  if (!args.client_id && !args.client_name) return errEnv("client_history", "Informe client_id ou client_name");
  let client = null;
  if (args.client_id) {
    const { data } = await scopeCompany(ctx.supabase.from("clients").select("*"), ctx).eq("id", args.client_id).maybeSingle();
    client = data;
  } else {
    const { data } = await scopeCompany(ctx.supabase.from("clients").select("*"), ctx).ilike("name", `%${args.client_name}%`).limit(1).maybeSingle();
    client = data;
  }
  if (!client) return errEnv("client_history", "Cliente n\xE3o encontrado");
  const [q, c, f] = await Promise.all([
    scopeCompany(ctx.supabase.from("quotes").select("id,quote_number,status,total,total_amount,created_at"), ctx).eq("client_id", client.id).order("created_at", { ascending: false }).limit(50),
    scopeCompany(ctx.supabase.from("generated_contracts").select("id,status,created_at"), ctx).eq("client_id", client.id).order("created_at", { ascending: false }).limit(20),
    scopeCompany(ctx.supabase.from("financial_records").select("id,status,amount,due_date"), ctx).eq("client_id", client.id).order("due_date", { ascending: false }).limit(50)
  ]);
  return okEnv("client_history", {
    data: { client, quotes: q.data ?? [], contracts: c.data ?? [], financial: f.data ?? [] }
  });
}
async function searchProducts(ctx, args = {}) {
  const term = args.query ?? args.search;
  const limit = Math.min(args.limit ?? 25, 200);
  let q = ctx.supabase.from("products").select("id,name,code,sku,brand,category_principal,price,level").order("name", { ascending: true }).limit(limit);
  q = scopeCompany(q, ctx);
  if (term) {
    const like = `%${term}%`;
    q = q.or(`name.ilike.${like},code.ilike.${like},sku.ilike.${like},brand.ilike.${like},description.ilike.${like}`);
  }
  if (args.brand) q = q.ilike("brand", `%${args.brand}%`);
  if (args.category) q = q.ilike("category_principal", `%${args.category}%`);
  const { data, error } = await q;
  if (error) return errEnv("products", error.message);
  return okEnv("products", {
    columns: ["name", "code", "brand", "category_principal", "price"],
    rows: data ?? [],
    count: data?.length ?? 0
  });
}
async function getProductDetails(ctx, args) {
  const { data, error } = await scopeCompany(ctx.supabase.from("products").select("*"), ctx).eq("id", args.id).maybeSingle();
  if (error) return errEnv("product", error.message);
  if (!data) return errEnv("product", "Produto n\xE3o encontrado");
  return okEnv("product", { data });
}
async function listQuotes(ctx, args = {}) {
  const limit = Math.min(args.limit ?? 25, 200);
  let q = ctx.supabase.from("quotes").select("id,quote_number,client_name,status,total,total_amount,created_at,created_by").order("quote_date", { ascending: false, nullsFirst: false }).order("created_at", { ascending: false }).limit(limit);
  q = scopeOwn(q, "created_by", ctx, args.scope);
  if (args.status) q = q.eq("status", args.status);
  const { data, error } = await q;
  if (error) return errEnv("quotes", error.message);
  return okEnv("quotes", {
    columns: ["quote_number", "client_name", "total_amount", "status", "created_at"],
    rows: data ?? [],
    count: data?.length ?? 0
  });
}
async function searchQuotes(ctx, args) {
  const limit = Math.min(args.limit ?? 25, 200);
  let q = ctx.supabase.from("quotes").select("id,quote_number,client_name,status,total,total_amount,created_at,created_by").order("created_at", { ascending: false }).limit(limit);
  q = scopeOwn(q, "created_by", ctx, args.scope);
  if (args.client_name) q = q.ilike("client_name", `%${args.client_name}%`);
  if (args.status) q = q.eq("status", args.status);
  if (args.from) q = q.gte("created_at", args.from);
  if (args.to) q = q.lte("created_at", args.to);
  const { data, error } = await q;
  if (error) return errEnv("quotes", error.message);
  return okEnv("quotes", { rows: data ?? [], count: data?.length ?? 0 });
}
async function getPipeline(ctx, args = {}) {
  let q = ctx.supabase.from("quotes").select("id,quote_number,client_name,status,total,total_amount,created_at,created_by").in("status", ["draft", "sent", "negotiation", "negociacao", "pre_sale", "contact_made"]).order("created_at", { ascending: false }).limit(500);
  q = scopeOwn(q, "created_by", ctx, args.scope);
  const { data, error } = await q;
  if (error) return errEnv("pipeline", error.message);
  const byStage = {};
  for (const r of data ?? []) {
    const s = r.status ?? "sem_status";
    byStage[s] ??= { count: 0, value: 0, items: [] };
    byStage[s].count += 1;
    byStage[s].value += Number(r.total_amount ?? r.total ?? 0);
    if (byStage[s].items.length < 20) byStage[s].items.push(r);
  }
  return okEnv("pipeline", { summary: byStage, rows: data ?? [], count: data?.length ?? 0 });
}
async function getDashboard(ctx) {
  const [clientsRes, quotesRes] = await Promise.all([
    scopeOwn(ctx.supabase.from("clients").select("id", { count: "exact", head: true }), "salesperson_id", ctx),
    scopeOwn(ctx.supabase.from("quotes").select("status,total,total_amount,created_at"), "created_by", ctx).limit(2e3)
  ]);
  if (quotesRes.error) return errEnv("dashboard", quotesRes.error.message);
  const byStatus = {};
  let grand = 0;
  for (const q of quotesRes.data ?? []) {
    const s = q.status ?? "sem_status";
    const v = Number(q.total_amount ?? q.total ?? 0);
    byStatus[s] ??= { count: 0, total: 0 };
    byStatus[s].count += 1;
    byStatus[s].total += v;
    grand += v;
  }
  return okEnv("dashboard", {
    summary: {
      total_clients: clientsRes.count ?? 0,
      total_quotes: quotesRes.data?.length ?? 0,
      forecast_total: grand,
      quotes_by_status: byStatus
    }
  });
}
async function getSalesMetrics(ctx, args = {}) {
  const from = args.from ?? (args.days_back ? new Date(Date.now() - args.days_back * 864e5).toISOString() : void 0);
  let q = ctx.supabase.from("quotes").select("id,status,total,total_amount,client_name,created_at,created_by").in("status", APPROVED_STATUSES).limit(5e3);
  q = scopeOwn(q, "created_by", ctx, args.scope);
  if (from) q = q.gte("created_at", from);
  if (args.to) q = q.lte("created_at", args.to);
  const { data, error } = await q;
  if (error) return errEnv("sales_metrics", error.message);
  const total = (data ?? []).reduce((s, r) => s + Number(r.total_amount ?? r.total ?? 0), 0);
  const count = data?.length ?? 0;
  return okEnv("sales_metrics", {
    summary: {
      approved_count: count,
      revenue_total: total,
      average_ticket: count ? total / count : 0,
      period: { from: from ?? null, to: args.to ?? null }
    }
  });
}
async function getTopProducts(ctx, args = {}) {
  const limit = Math.min(args.limit ?? 10, 50);
  const metric = args.metric ?? "revenue";
  const from = args.from ?? (args.days_back ? new Date(Date.now() - args.days_back * 864e5).toISOString() : void 0);
  const fmtDate = (iso) => {
    try {
      const d = new Date(iso);
      return `${String(d.getDate()).padStart(2, "0")}/${String(d.getMonth() + 1).padStart(2, "0")}/${d.getFullYear()}`;
    } catch {
      return iso;
    }
  };
  let periodLabel = "Todo o hist\xF3rico";
  if (args.days_back) periodLabel = `\xDAltimos ${args.days_back} dias`;
  else if (from && args.to) periodLabel = `${fmtDate(from)} at\xE9 ${fmtDate(args.to)}`;
  else if (from) {
    const d = new Date(from);
    const now = /* @__PURE__ */ new Date();
    if (d.getFullYear() === now.getFullYear() && d.getMonth() === now.getMonth() && d.getDate() === 1) periodLabel = "Este m\xEAs";
    else if (d.getFullYear() === now.getFullYear() && d.getMonth() === 0 && d.getDate() === 1) periodLabel = "Este ano";
    else periodLabel = `A partir de ${fmtDate(from)}`;
  } else if (args.to) periodLabel = `At\xE9 ${fmtDate(args.to)}`;
  let qq = ctx.supabase.from("quotes").select("id,created_by,created_at,status").in("status", APPROVED_STATUSES).limit(5e3);
  qq = scopeOwn(qq, "created_by", ctx, args.scope);
  if (from) qq = qq.gte("created_at", from);
  if (args.to) qq = qq.lte("created_at", args.to);
  const { data: quotes, error: qErr } = await qq;
  if (qErr) return errEnv("top_products", qErr.message);
  if (!quotes || quotes.length === 0) {
    return okEnv("top_products", { rows: [], count: 0, summary: { metric, period_label: periodLabel, approved_quotes_scanned: 0 } });
  }
  const quoteIds = quotes.map((q) => q.id);
  let ii = ctx.supabase.from("quote_items").select("quote_id,code,product_code,description,brand,quantity,line_total,total_price,unit_total,unit_price,image_url,model").in("quote_id", quoteIds).limit(2e4);
  if (args.brand) ii = ii.ilike("brand", `%${args.brand}%`);
  const { data: items, error: iErr } = await ii;
  if (iErr) return errEnv("top_products", iErr.message);
  const looksLikeName = (s) => typeof s === "string" && s.trim().length >= 3 && !/^\d+$/.test(s.trim());
  const agg = {};
  for (const it of items ?? []) {
    const code = (it.product_code || it.code || "").toString().trim() || null;
    const rawDesc = (it.description || "").toString().trim();
    const itemName = looksLikeName(rawDesc) ? rawDesc : null;
    const key = (code || itemName || rawDesc || "sem-chave").toLowerCase();
    const qty = Number(it.quantity ?? 0);
    const rev = Number(it.line_total ?? it.total_price ?? it.unit_total ?? Number(it.unit_price ?? 0) * qty);
    agg[key] ??= { key, code, itemName, itemBrand: it.brand ?? null, itemImage: it.image_url ?? null, quantity: 0, revenue: 0, quotes: /* @__PURE__ */ new Set() };
    agg[key].quantity += qty;
    agg[key].revenue += rev;
    agg[key].quotes.add(it.quote_id);
  }
  const codes = Array.from(new Set(Object.values(agg).map((r) => r.code).filter(Boolean)));
  const productByCode = {};
  const productBySku = {};
  if (codes.length > 0) {
    const chunk = 200;
    for (let i = 0; i < codes.length; i += chunk) {
      const slice = codes.slice(i, i + chunk);
      const { data: prods } = await ctx.supabase.from("products").select("id,name,brand,sku,code,image_url").or(`code.in.(${slice.map((c) => `"${c.replace(/"/g, "")}"`).join(",")}),sku.in.(${slice.map((c) => `"${c.replace(/"/g, "")}"`).join(",")})`);
      for (const p of prods ?? []) {
        if (p.code) productByCode[String(p.code).toLowerCase()] = p;
        if (p.sku) productBySku[String(p.sku).toLowerCase()] = p;
      }
    }
  }
  const totalRevenue = Object.values(agg).reduce((s, r) => s + r.revenue, 0);
  const totalQty = Object.values(agg).reduce((s, r) => s + r.quantity, 0);
  const rows = Object.values(agg).map((r) => {
    const codeKey = r.code?.toLowerCase();
    const prod = codeKey && (productByCode[codeKey] || productBySku[codeKey]) || null;
    const name = prod?.name && String(prod.name).trim() || r.itemName && String(r.itemName).trim() || "Produto sem nome cadastrado";
    const brand = prod?.brand || r.itemBrand || null;
    const sku = prod?.sku || null;
    const image_url = prod?.image_url || r.itemImage || null;
    const avg = r.quantity > 0 ? r.revenue / r.quantity : 0;
    const share = metric === "quantity" ? totalQty > 0 ? r.quantity / totalQty * 100 : 0 : totalRevenue > 0 ? r.revenue / totalRevenue * 100 : 0;
    return {
      product_id: prod?.id ?? null,
      product_code: prod?.code ?? r.code ?? null,
      sku,
      product_name: name,
      brand,
      image_url,
      quantity_sold: r.quantity,
      revenue: r.revenue,
      approved_quotes_count: r.quotes.size,
      average_price: avg,
      share_pct: Number(share.toFixed(2))
    };
  }).sort((a, b) => metric === "quantity" ? b.quantity_sold - a.quantity_sold : b.revenue - a.revenue).slice(0, limit).map((r, idx) => ({ ranking_position: idx + 1, ...r }));
  return okEnv("top_products", {
    columns: ["ranking_position", "image_url", "product_name", "brand", "sku", "quantity_sold", "revenue", "approved_quotes_count", "average_price", "share_pct"],
    rows,
    count: rows.length,
    summary: { metric, period_label: periodLabel, approved_quotes_scanned: quotes.length }
  });
}
async function getTopBrands(ctx, args = {}) {
  const limit = Math.min(args.limit ?? 10, 50);
  const from = args.from ?? (args.days_back ? new Date(Date.now() - args.days_back * 864e5).toISOString() : void 0);
  const fmtDate = (iso) => {
    try {
      const d = new Date(iso);
      return `${String(d.getDate()).padStart(2, "0")}/${String(d.getMonth() + 1).padStart(2, "0")}/${d.getFullYear()}`;
    } catch {
      return iso;
    }
  };
  let periodLabel = "Todo o hist\xF3rico";
  if (args.days_back) periodLabel = `\xDAltimos ${args.days_back} dias`;
  else if (from && args.to) periodLabel = `${fmtDate(from)} at\xE9 ${fmtDate(args.to)}`;
  else if (from) periodLabel = `A partir de ${fmtDate(from)}`;
  let qq = ctx.supabase.from("quotes").select("id,client_id,created_by,created_at,status").in("status", APPROVED_STATUSES).limit(5e3);
  qq = scopeOwn(qq, "created_by", ctx, args.scope);
  if (from) qq = qq.gte("created_at", from);
  if (args.to) qq = qq.lte("created_at", args.to);
  const { data: quotes, error: qErr } = await qq;
  if (qErr) return errEnv("top_brands", qErr.message);
  if (!quotes?.length) return okEnv("top_brands", { rows: [], count: 0, summary: { period_label: periodLabel } });
  const quoteIds = quotes.map((q) => q.id);
  const clientByQuote = {};
  quotes.forEach((q) => {
    clientByQuote[q.id] = q.client_id ?? null;
  });
  const { data: items, error: iErr } = await ctx.supabase.from("quote_items").select("quote_id,brand,product_code,code,quantity,line_total,total_price,unit_total,unit_price").in("quote_id", quoteIds).limit(2e4);
  if (iErr) return errEnv("top_brands", iErr.message);
  const codes = Array.from(new Set((items ?? []).map((it) => (it.product_code || it.code || "").toString().trim().toLowerCase()).filter(Boolean)));
  const brandByCode = {};
  if (codes.length) {
    for (let i = 0; i < codes.length; i += 200) {
      const slice = codes.slice(i, i + 200);
      const { data: prods } = await scopeCompany(ctx.supabase.from("products").select("code,sku,brand"), ctx).or(`code.in.(${slice.map((c) => `"${c.replace(/"/g, "")}"`).join(",")}),sku.in.(${slice.map((c) => `"${c.replace(/"/g, "")}"`).join(",")})`);
      for (const p of prods ?? []) {
        if (p.brand) {
          if (p.code) brandByCode[String(p.code).toLowerCase()] = p.brand;
          if (p.sku) brandByCode[String(p.sku).toLowerCase()] = p.brand;
        }
      }
    }
  }
  const agg = {};
  for (const it of items ?? []) {
    const rawCode = (it.product_code || it.code || "").toString().trim().toLowerCase();
    const brand = it.brand?.toString().trim() || brandByCode[rawCode] || null;
    if (!brand) continue;
    const key = brand.toLowerCase();
    const qty = Number(it.quantity ?? 0);
    const rev = Number(it.line_total ?? it.total_price ?? it.unit_total ?? Number(it.unit_price ?? 0) * qty);
    agg[key] ??= { brand, quantity: 0, revenue: 0, quotes: /* @__PURE__ */ new Set(), clients: /* @__PURE__ */ new Set() };
    agg[key].quantity += qty;
    agg[key].revenue += rev;
    agg[key].quotes.add(it.quote_id);
    const cid = clientByQuote[it.quote_id];
    if (cid) agg[key].clients.add(cid);
  }
  const totalRev = Object.values(agg).reduce((s, r) => s + r.revenue, 0);
  const rows = Object.values(agg).map((r) => ({
    brand: r.brand,
    quantity_sold: r.quantity,
    revenue: r.revenue,
    approved_quotes_count: r.quotes.size,
    customer_count: r.clients.size,
    participation_percentage: totalRev > 0 ? Number((r.revenue / totalRev * 100).toFixed(2)) : 0
  })).sort((a, b) => b.revenue - a.revenue).slice(0, limit);
  return okEnv("top_brands", {
    columns: ["brand", "quantity_sold", "revenue", "customer_count", "approved_quotes_count", "participation_percentage"],
    rows,
    count: rows.length,
    summary: { period_label: periodLabel, approved_quotes_scanned: quotes.length }
  });
}
async function getInactiveClients(ctx, args = {}) {
  const inactiveDays = args.inactive_days ?? 90;
  const minRevenue = args.minimum_revenue ?? 0;
  const limit = Math.min(args.limit ?? 20, 100);
  const cutoff = new Date(Date.now() - inactiveDays * 864e5);
  let qq = ctx.supabase.from("quotes").select("id,client_id,client_name,total,total_amount,approved_at,created_at,created_by,salesperson,status").in("status", APPROVED_STATUSES).limit(1e4);
  qq = scopeOwn(qq, "created_by", ctx, args.scope);
  if (args.period_start) qq = qq.gte("created_at", args.period_start);
  if (args.period_end) qq = qq.lte("created_at", args.period_end);
  const { data: quotes, error } = await qq;
  if (error) return errEnv("inactive_clients", error.message);
  const map = /* @__PURE__ */ new Map();
  for (const q of quotes ?? []) {
    const cid = q.client_id;
    if (!cid) continue;
    const d = new Date(q.approved_at || q.created_at);
    const v = Number(q.total_amount ?? q.total ?? 0);
    const cur = map.get(cid);
    if (!cur) map.set(cid, { client_id: cid, client_name: q.client_name || "Sem cliente", last: d, count: 1, revenue: v, seller: q.salesperson ?? null });
    else {
      cur.count++;
      cur.revenue += v;
      if (d > cur.last) cur.last = d;
    }
  }
  const rows = Array.from(map.values()).filter((r) => r.last < cutoff && r.revenue >= minRevenue).sort((a, b) => b.revenue - a.revenue).slice(0, limit).map((r) => {
    const days = Math.floor((Date.now() - r.last.getTime()) / 864e5);
    return {
      client_id: r.client_id,
      client_name: r.client_name,
      last_purchase_date: r.last.toISOString(),
      days_inactive: days,
      total_revenue: r.revenue,
      total_purchases: r.count,
      seller_name: r.seller,
      recommended_action: days >= 180 ? "Reengajamento urgente" : "Follow-up comercial"
    };
  });
  return okEnv("inactive_clients", {
    columns: ["client_name", "last_purchase_date", "days_inactive", "total_revenue", "total_purchases", "seller_name", "recommended_action"],
    rows,
    count: rows.length,
    summary: { inactive_days: inactiveDays, minimum_revenue: minRevenue }
  });
}
async function getRepurchaseWindow(ctx, args = {}) {
  const minPurchases = Math.max(args.min_purchases ?? 2, 2);
  const tol = args.tolerance_pct ?? 0.3;
  const limit = Math.min(args.limit ?? 20, 100);
  let qq = ctx.supabase.from("quotes").select("id,client_id,client_name,total,total_amount,approved_at,created_at,created_by,status").in("status", APPROVED_STATUSES).limit(1e4);
  qq = scopeOwn(qq, "created_by", ctx, args.scope);
  const { data: quotes, error } = await qq;
  if (error) return errEnv("repurchase_window", error.message);
  const map = /* @__PURE__ */ new Map();
  for (const q of quotes ?? []) {
    const cid = q.client_id;
    if (!cid) continue;
    const d = new Date(q.approved_at || q.created_at);
    const cur = map.get(cid);
    if (!cur) map.set(cid, { client_id: cid, client_name: q.client_name || "Sem cliente", dates: [d] });
    else cur.dates.push(d);
  }
  const now = Date.now();
  const rows = [];
  for (const r of map.values()) {
    if (r.dates.length < minPurchases) continue;
    r.dates.sort((a, b) => a.getTime() - b.getTime());
    const first = r.dates[0], last = r.dates[r.dates.length - 1];
    const avgDays = Math.round((last.getTime() - first.getTime()) / 864e5 / (r.dates.length - 1));
    if (avgDays <= 0) continue;
    const expected = new Date(last.getTime() + avgDays * 864e5);
    const daysUntil = Math.floor((expected.getTime() - now) / 864e5);
    const daysSinceLast = Math.floor((now - last.getTime()) / 864e5);
    const inWindow = daysSinceLast >= avgDays * (1 - tol) && daysSinceLast <= avgDays * (1 + tol);
    if (!inWindow) continue;
    const confidence = r.dates.length >= 4 ? "alta" : r.dates.length >= 3 ? "m\xE9dia" : "baixa";
    rows.push({
      client_id: r.client_id,
      client_name: r.client_name,
      last_purchase_date: last.toISOString(),
      average_purchase_interval_days: avgDays,
      expected_repurchase_date: expected.toISOString(),
      days_until_repurchase: daysUntil,
      confidence,
      recommended_action: daysUntil <= 0 ? "Abordagem imediata" : "Preparar oferta"
    });
  }
  rows.sort((a, b) => a.days_until_repurchase - b.days_until_repurchase);
  return okEnv("repurchase_window", {
    columns: ["client_name", "last_purchase_date", "average_purchase_interval_days", "expected_repurchase_date", "days_until_repurchase", "confidence", "recommended_action"],
    rows: rows.slice(0, limit),
    count: Math.min(rows.length, limit),
    summary: { min_purchases: minPurchases, tolerance_pct: tol }
  });
}
var COUNTABLE_STATUSES = new Set(APPROVED_STATUSES);
async function getCommercialOverview(ctx, args = {}) {
  const role = ctx.profile?.role;
  const canSeeAll = role === "admin" || role === "gestor";
  const wantsTeam = canSeeAll && (args.scope ?? "team") !== "own";
  const limit = Math.min(args.limit ?? 5e3, 1e4);
  let qq = ctx.supabase.from("quotes").select("id, quote_number, client_id, client_name, salesperson, salesperson_id, created_by, status, payment_status, total_amount, total, approved_at, created_at, is_demonstration").order("created_at", { ascending: false }).limit(limit);
  qq = scopeOwn(qq, "created_by", ctx, wantsTeam ? "team" : "own");
  const { data: quotesRaw, error: qErr } = await qq;
  if (qErr) return errEnv("commercial_overview", qErr.message);
  const validQuotes = (quotesRaw ?? []).filter((q) => {
    if (q.is_demonstration) return false;
    const s = (q.status ?? "").toLowerCase().trim();
    return COUNTABLE_STATUSES.has(s);
  });
  const [clientsRes, productsRes, profilesRes] = await Promise.all([
    scopeCompany(ctx.supabase.from("clients").select("id, name, company_name, contact_name, email, phone, contact_phone, city, state, cpf_cnpj, created_by"), ctx),
    scopeCompany(ctx.supabase.from("products").select("id, name, brand, code, sku"), ctx),
    wantsTeam ? scopeCompany(ctx.supabase.from("profiles").select("user_id, full_name, active").eq("active", true), ctx) : Promise.resolve({ data: [], error: null })
  ]);
  if (clientsRes.error) return errEnv("commercial_overview", clientsRes.error.message);
  if (productsRes.error) return errEnv("commercial_overview", productsRes.error.message);
  if (profilesRes.error) return errEnv("commercial_overview", profilesRes.error.message);
  const clients = {};
  for (const c of clientsRes.data ?? []) clients[c.id] = c;
  const quoteIds = validQuotes.map((q) => q.id);
  const items = [];
  const CHUNK = 200;
  for (let i = 0; i < quoteIds.length; i += CHUNK) {
    const slice = quoteIds.slice(i, i + CHUNK);
    const { data, error } = await ctx.supabase.from("quote_items").select("quote_id, code, product_code, description, brand, model, quantity, unit_price, total_price, line_total, unit_total").in("quote_id", slice);
    if (error) return errEnv("commercial_overview", error.message);
    if (data) items.push(...data);
  }
  const sellerProfiles = (profilesRes.data ?? []).map((p) => ({
    user_id: p.user_id,
    full_name: p.full_name || "Vendedor"
  }));
  return okEnv("commercial_overview", {
    data: {
      quotes: validQuotes,
      clients,
      items,
      products: productsRes.data ?? [],
      sellerProfiles,
      loadedAt: Date.now(),
      scope: wantsTeam ? "team" : "own"
    },
    summary: {
      quotes_count: validQuotes.length,
      items_count: items.length,
      clients_count: Object.keys(clients).length,
      scope: wantsTeam ? "team" : "own"
    }
  });
}
async function getClientRanking(ctx, args = {}) {
  const overview = await getCommercialOverview(ctx, { scope: args.scope });
  if (!overview.ok) return overview;
  const payload = overview.data ?? {};
  const quotes = payload.quotes ?? [];
  const clients = payload.clients ?? {};
  const items = payload.items ?? [];
  const products = payload.products ?? [];
  const productByCode = /* @__PURE__ */ new Map();
  for (const p of products) {
    if (p?.code) productByCode.set(String(p.code).toLowerCase(), p);
    if (p?.sku) productByCode.set(String(p.sku).toLowerCase(), p);
  }
  const itemsByQuote = /* @__PURE__ */ new Map();
  for (const it of items) {
    const arr = itemsByQuote.get(it.quote_id) ?? [];
    arr.push(it);
    itemsByQuote.set(it.quote_id, arr);
  }
  const now = Date.now();
  const period = args.period_days === "all" || !args.period_days ? null : Number(args.period_days);
  const filtered = quotes.filter((q) => {
    if (period != null) {
      const d = new Date(q.approved_at || q.created_at).getTime();
      if (now - d > period * 864e5) return false;
    }
    if (args.seller_id && args.seller_id !== "all") {
      if (q.salesperson_id !== args.seller_id && q.created_by !== args.seller_id) return false;
    }
    if (args.state && args.state !== "all") {
      const c = q.client_id ? clients[q.client_id] : null;
      if ((c?.state ?? "") !== args.state) return false;
    }
    if (args.city && args.city !== "all") {
      const c = q.client_id ? clients[q.client_id] : null;
      if ((c?.city ?? "") !== args.city) return false;
    }
    return true;
  });
  const itemValue = (it) => {
    const tp = Number(it.total_price || 0);
    if (tp > 0) return tp;
    const lt = Number(it.line_total || 0);
    if (lt > 0) return lt;
    const ut = Number(it.unit_total || 0);
    if (ut > 0) return ut;
    const up = Number(it.unit_price || 0);
    const qty = Number(it.quantity || 0) || 1;
    return up * qty;
  };
  const qValue = (q) => Number(q.total_amount ?? q.total ?? 0);
  const map = /* @__PURE__ */ new Map();
  for (const q of filtered) {
    const cid = q.client_id || `__${q.client_name || "sem"}`;
    const c = q.client_id ? clients[q.client_id] ?? null : null;
    let a = map.get(cid);
    if (!a) {
      a = {
        client_id: cid,
        client_name: c?.company_name || c?.name || q.client_name || "Sem cliente",
        cnpj: c?.cpf_cnpj || "",
        city: c?.city || "",
        state: c?.state || "",
        salesperson: q.salesperson || "",
        quotes_count: 0,
        total_value: 0,
        received_value: 0,
        first_purchase: null,
        last_purchase: null,
        monthly: {},
        brands: {},
        products: {}
      };
      map.set(cid, a);
    }
    const val = qValue(q);
    const dateStr = q.approved_at || q.created_at;
    const d = new Date(dateStr);
    a.quotes_count += 1;
    a.total_value += val;
    if ((q.payment_status ?? "").toLowerCase() === "liquidado") a.received_value += val;
    if (!a.first_purchase || d < new Date(a.first_purchase)) a.first_purchase = dateStr;
    if (!a.last_purchase || d > new Date(a.last_purchase)) a.last_purchase = dateStr;
    const mk = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
    a.monthly[mk] = (a.monthly[mk] || 0) + val;
    for (const it of itemsByQuote.get(q.id) ?? []) {
      const rawCode = String(it.code || it.product_code || "").trim();
      const prod = rawCode ? productByCode.get(rawCode.toLowerCase()) : void 0;
      const desc = (it.description || "").trim();
      const name = prod?.name?.trim() || desc || rawCode || "Item sem nome";
      const brand = prod?.brand?.trim() || it.brand || "Sem marca";
      const v = itemValue(it);
      a.brands[brand] = (a.brands[brand] || 0) + v;
      const key = (rawCode || desc || name).toLowerCase();
      if (!a.products[key]) a.products[key] = { qty: 0, value: 0, name, brand };
      a.products[key].qty += Number(it.quantity || 0);
      a.products[key].value += v;
    }
  }
  const rows = Array.from(map.values()).map((a) => {
    const ticket = a.quotes_count ? a.total_value / a.quotes_count : 0;
    const lastDate = a.last_purchase ? new Date(a.last_purchase) : null;
    const firstDate = a.first_purchase ? new Date(a.first_purchase) : null;
    const daysSinceLast = lastDate ? Math.floor((now - lastDate.getTime()) / 864e5) : null;
    const intervalAvgDays = firstDate && lastDate && a.quotes_count > 1 ? Math.round(Math.floor((lastDate.getTime() - firstDate.getTime()) / 864e5) / (a.quotes_count - 1)) : null;
    const isActive = (daysSinceLast ?? 9999) <= 90;
    const isRecurrent = a.quotes_count >= 2;
    const status = (daysSinceLast ?? 9999) <= 30 ? "verde" : (daysSinceLast ?? 9999) <= 90 ? "amarelo" : "vermelho";
    const topProducts = Object.values(a.products).sort((x, y) => y.value - x.value).slice(0, 5);
    return {
      ...a,
      ticket_medio: ticket,
      days_since_last: daysSinceLast,
      interval_avg_days: intervalAvgDays,
      is_active: isActive,
      is_recurrent: isRecurrent,
      status,
      top_products: topProducts
    };
  }).filter((a) => {
    if (args.only_recurrent && !a.is_recurrent) return false;
    if (args.active_filter === "active" && !a.is_active) return false;
    if (args.active_filter === "inactive" && a.is_active) return false;
    return true;
  }).sort((x, y) => y.total_value - x.total_value);
  const limit = Math.min(args.limit ?? 500, 2e3);
  const trimmed = rows.slice(0, limit);
  return okEnv("client_ranking", {
    rows: trimmed,
    count: trimmed.length,
    summary: {
      total_clients: rows.length,
      active_clients: rows.filter((a) => a.is_active).length,
      recurrent_clients: rows.filter((a) => a.is_recurrent).length,
      total_revenue: rows.reduce((s, a) => s + a.total_value, 0),
      period_days: args.period_days ?? "all",
      scope: payload.scope
    }
  });
}
async function getFollowups(ctx, args = {}) {
  const days = args.days_without_contact ?? 30;
  const limit = Math.min(args.limit ?? 25, 200);
  const cutoff = new Date(Date.now() - days * 864e5).toISOString();
  const { data, error } = await ctx.supabase.from("clients").select("id,name,company_name,email,phone,last_interaction_at").or(`last_interaction_at.lt.${cutoff},last_interaction_at.is.null`).order("last_interaction_at", { ascending: true, nullsFirst: true }).limit(limit);
  if (error) return errEnv("followups", error.message);
  return okEnv("followups", {
    columns: ["company_name", "name", "phone", "last_interaction_at"],
    rows: data ?? [],
    count: data?.length ?? 0
  });
}
async function getTasks(ctx, args = {}) {
  const limit = Math.min(args.limit ?? 25, 200);
  let q = ctx.supabase.from("tasks").select("id,title,description,status,priority,due_date,client_id,user_id,created_at").order("due_date", { ascending: true, nullsFirst: false }).limit(limit);
  if (args.status) q = q.eq("status", args.status);
  if (args.overdue_only) q = q.lt("due_date", (/* @__PURE__ */ new Date()).toISOString()).neq("status", "done");
  const { data, error } = await q;
  if (error) return errEnv("tasks", error.message);
  return okEnv("tasks", {
    columns: ["title", "due_date", "status", "priority"],
    rows: data ?? [],
    count: data?.length ?? 0
  });
}
async function getContracts(ctx, args = {}) {
  const limit = Math.min(args.limit ?? 25, 200);
  let q = ctx.supabase.from("generated_contracts").select("*").order("created_at", { ascending: false }).limit(limit);
  if (args.status) q = q.eq("status", args.status);
  const { data, error } = await q;
  if (error) return errEnv("contracts", error.message);
  return okEnv("contracts", { rows: data ?? [], count: data?.length ?? 0 });
}
var TOOL_REGISTRY = {
  list_clients: {
    name: "list_clients",
    description: "Lista clientes da carteira do usu\xE1rio. Use scope='team' apenas se admin/gestor pedir a equipe inteira.",
    parameters: { type: "object", properties: { search: { type: "string" }, limit: { type: "number" }, scope: { type: "string", enum: ["own", "team"] } } },
    handler: listClients,
    readOnly: true,
    aliases: ["get_clients"]
  },
  search_clients: {
    name: "search_clients",
    description: "Busca clientes por nome, empresa, e-mail, telefone, cidade, CPF ou CNPJ.",
    parameters: { type: "object", required: ["query"], properties: { query: { type: "string" }, limit: { type: "number" } } },
    handler: searchClients,
    readOnly: true
  },
  get_customer_history: {
    name: "get_customer_history",
    description: "Hist\xF3rico completo de um cliente (or\xE7amentos, contratos, financeiro).",
    parameters: { type: "object", properties: { client_id: { type: "string" }, client_name: { type: "string" } } },
    handler: getCustomerHistory,
    readOnly: true
  },
  search_products: {
    name: "search_products",
    description: "Busca produtos por nome, c\xF3digo, SKU, marca, descri\xE7\xE3o ou categoria.",
    parameters: { type: "object", properties: { query: { type: "string" }, brand: { type: "string" }, category: { type: "string" }, limit: { type: "number" } } },
    handler: searchProducts,
    readOnly: true,
    aliases: ["get_products", "list_products"]
  },
  get_product_details: {
    name: "get_product_details",
    description: "Retorna todos os dados do produto MCI pelo id.",
    parameters: { type: "object", required: ["id"], properties: { id: { type: "string" } } },
    handler: getProductDetails,
    readOnly: true
  },
  list_quotes: {
    name: "list_quotes",
    description: "Lista or\xE7amentos da carteira do usu\xE1rio. Aceita filtro por status.",
    parameters: { type: "object", properties: { status: { type: "string" }, limit: { type: "number" }, scope: { type: "string", enum: ["own", "team"] } } },
    handler: listQuotes,
    readOnly: true,
    aliases: ["get_quotes"]
  },
  search_quotes: {
    name: "search_quotes",
    description: "Busca or\xE7amentos por cliente, status, per\xEDodo (from/to ISO).",
    parameters: { type: "object", properties: { client_name: { type: "string" }, status: { type: "string" }, from: { type: "string" }, to: { type: "string" }, limit: { type: "number" }, scope: { type: "string", enum: ["own", "team"] } } },
    handler: searchQuotes,
    readOnly: true
  },
  get_pipeline: {
    name: "get_pipeline",
    description: "Or\xE7amentos abertos agrupados por est\xE1gio do pipeline.",
    parameters: { type: "object", properties: { scope: { type: "string", enum: ["own", "team"] } } },
    handler: getPipeline,
    readOnly: true
  },
  get_dashboard: {
    name: "get_dashboard",
    description: "Dashboard executivo: totais de clientes, or\xE7amentos por status, valor previsto.",
    parameters: { type: "object", properties: {} },
    handler: getDashboard,
    readOnly: true
  },
  get_sales_metrics: {
    name: "get_sales_metrics",
    description: "M\xE9tricas de vendas (or\xE7amentos aprovados): receita total, ticket m\xE9dio. Aceita from/to ou days_back.",
    parameters: { type: "object", properties: { from: { type: "string" }, to: { type: "string" }, days_back: { type: "number" }, scope: { type: "string", enum: ["own", "team"] } } },
    handler: getSalesMetrics,
    readOnly: true,
    aliases: ["get_metrics"]
  },
  get_top_products: {
    name: "get_top_products",
    description: "Ranking de produtos mais vendidos (apenas or\xE7amentos aprovados). metric='quantity' ou 'revenue'.",
    parameters: {
      type: "object",
      properties: {
        from: { type: "string" },
        to: { type: "string" },
        days_back: { type: "number" },
        metric: { type: "string", enum: ["quantity", "revenue"] },
        brand: { type: "string" },
        limit: { type: "number" },
        scope: { type: "string", enum: ["own", "team"] }
      }
    },
    handler: getTopProducts,
    readOnly: true
  },
  get_followups: {
    name: "get_followups",
    description: "Clientes sem intera\xE7\xE3o recente (default 30 dias) para follow-up.",
    parameters: { type: "object", properties: { days_without_contact: { type: "number" }, limit: { type: "number" } } },
    handler: getFollowups,
    readOnly: true
  },
  get_tasks: {
    name: "get_tasks",
    description: "Lista tarefas do usu\xE1rio. overdue_only=true traz apenas vencidas n\xE3o conclu\xEDdas.",
    parameters: { type: "object", properties: { status: { type: "string" }, overdue_only: { type: "boolean" }, limit: { type: "number" } } },
    handler: getTasks,
    readOnly: true
  },
  get_contracts: {
    name: "get_contracts",
    description: "Lista contratos gerados e status de assinatura.",
    parameters: { type: "object", properties: { status: { type: "string" }, limit: { type: "number" } } },
    handler: getContracts,
    readOnly: true
  },
  get_top_brands: {
    name: "get_top_brands",
    description: "Ranking de marcas mais vendidas (or\xE7amentos aprovados). Retorna receita, unidades, clientes e participa\xE7\xE3o %.",
    parameters: { type: "object", properties: { from: { type: "string" }, to: { type: "string" }, days_back: { type: "number" }, limit: { type: "number" }, scope: { type: "string", enum: ["own", "team"] } } },
    handler: getTopBrands,
    readOnly: true
  },
  get_inactive_clients: {
    name: "get_inactive_clients",
    description: "Clientes sem compra aprovada h\xE1 X dias (default 90). Retorna dias inativos, receita hist\xF3rica, vendedor e a\xE7\xE3o recomendada.",
    parameters: { type: "object", properties: { inactive_days: { type: "number" }, minimum_revenue: { type: "number" }, limit: { type: "number" }, scope: { type: "string", enum: ["own", "team"] }, period_start: { type: "string" }, period_end: { type: "string" } } },
    handler: getInactiveClients,
    readOnly: true,
    aliases: ["inactive_clients"]
  },
  get_repurchase_window: {
    name: "get_repurchase_window",
    description: "Clientes em janela de recompra: intervalo m\xE9dio entre compras aprovadas, data prevista, confian\xE7a e a\xE7\xE3o recomendada. Requer no m\xEDnimo 2 compras.",
    parameters: { type: "object", properties: { min_purchases: { type: "number" }, tolerance_pct: { type: "number" }, limit: { type: "number" }, scope: { type: "string", enum: ["own", "team"] } } },
    handler: getRepurchaseWindow,
    readOnly: true,
    aliases: ["recompute_repurchase", "repurchase_window"]
  },
  get_commercial_overview: {
    name: "get_commercial_overview",
    description: "Payload agregado da Intelig\xEAncia Comercial: quotes aprovados v\xE1lidos + clients + items + products + sellerProfiles. Substitui o SQL direto no navegador. scope='team' apenas para admin/gestor.",
    parameters: { type: "object", properties: { scope: { type: "string", enum: ["own", "team"] }, limit: { type: "number" } } },
    handler: getCommercialOverview,
    readOnly: true,
    aliases: ["commercial_overview", "intelligence_overview"]
  },
  get_client_ranking: {
    name: "get_client_ranking",
    description: "Ranking de clientes agregado no servidor (aba Rankings da Intelig\xEAncia Comercial): valor total, ticket m\xE9dio, marcas, top produtos, status, recorr\xEAncia, per\xEDodo configur\xE1vel.",
    parameters: {
      type: "object",
      properties: {
        scope: { type: "string", enum: ["own", "team"] },
        period_days: { type: ["number", "string"], description: "N\xFAmero de dias ou 'all'" },
        seller_id: { type: "string" },
        state: { type: "string" },
        city: { type: "string" },
        only_recurrent: { type: "boolean" },
        active_filter: { type: "string", enum: ["all", "active", "inactive"] },
        limit: { type: "number" }
      }
    },
    handler: getClientRanking,
    readOnly: true,
    aliases: ["client_ranking", "top_clients"]
  }
};
function resolveTool(name) {
  if (TOOL_REGISTRY[name]) return TOOL_REGISTRY[name];
  for (const t of Object.values(TOOL_REGISTRY)) {
    if (t.aliases?.includes(name)) return t;
  }
  return null;
}

// src/lib/mcp/_bridge.ts
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
  }
  return null;
}
async function loadProfile(supabase, userId) {
  const { data } = await supabase.from("profiles").select("full_name, role, company_id").eq("user_id", userId).maybeSingle();
  return data ?? null;
}
async function runShared(name, args, ctx) {
  const guard = requireAuth(ctx);
  if (guard) return guard;
  const tool = resolveTool(name);
  if (!tool) return { content: [{ type: "text", text: `Tool ${name} n\xE3o implementada` }], isError: true };
  const supabase = supabaseForUser(ctx);
  const userId = ctx.getUserId() ?? "";
  const profile = await loadProfile(supabase, userId);
  const crmCtx = { supabase, userId, profile, companyId: profile?.company_id ?? null };
  try {
    const res = await tool.handler(crmCtx, args ?? {});
    if (!res.ok) {
      return { content: [{ type: "text", text: res.error ?? "Erro desconhecido" }], isError: true };
    }
    const structured = { ok: true, entity: res.entity };
    if (res.rows !== void 0) structured.rows = res.rows;
    if (res.count !== void 0) structured.count = res.count;
    if (res.summary !== void 0) structured.summary = res.summary;
    if (res.data !== void 0) structured.data = res.data;
    if (res.columns !== void 0) structured.columns = res.columns;
    return {
      content: [{ type: "text", text: JSON.stringify(structured).slice(0, 12e3) }],
      structuredContent: structured
    };
  } catch (e) {
    return { content: [{ type: "text", text: e?.message ?? "Erro na execu\xE7\xE3o" }], isError: true };
  }
}

// src/lib/mcp/tools/list-clients.ts
var list_clients_default = defineTool({
  name: "list_clients",
  title: "Listar clientes",
  description: "Lista clientes do CRM vis\xEDveis ao usu\xE1rio autenticado.",
  inputSchema: {
    search: z.string().optional().describe("Filtro por nome/email/telefone"),
    limit: z.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (args, ctx) => runShared("list_clients", args, ctx)
});

// src/lib/mcp/tools/list-quotes.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_quotes_default = defineTool2({
  name: "list_quotes",
  title: "Listar or\xE7amentos",
  description: "Lista or\xE7amentos do CRM vis\xEDveis ao usu\xE1rio autenticado, opcionalmente filtrados por status.",
  inputSchema: {
    status: z2.string().optional().describe("Filtro por status (ex: aprovado, pendente)"),
    limit: z2.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (args, ctx) => runShared("list_quotes", args, ctx)
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var whoami_default = defineTool3({
  name: "whoami",
  title: "Quem sou eu",
  description: "Retorna informa\xE7\xF5es do usu\xE1rio autenticado via MCP.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const info = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/search-clients.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var search_clients_default = defineTool4({
  name: "search_clients",
  title: "Buscar clientes",
  description: "Busca clientes por nome, empresa, e-mail, telefone, cidade, CNPJ ou CPF respeitando permiss\xF5es (RLS).",
  inputSchema: {
    query: z3.string().min(1).describe("Termo de busca"),
    limit: z3.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (args, ctx) => runShared("search_clients", args, ctx)
});

// src/lib/mcp/tools/get-products.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var get_products_default = defineTool5({
  name: "get_products",
  title: "Listar produtos",
  description: "Lista produtos do cat\xE1logo MCI vis\xEDveis ao usu\xE1rio autenticado.",
  inputSchema: {
    search: z4.string().optional().describe("Filtro por nome/SKU/marca"),
    limit: z4.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (args, ctx) => runShared("search_products", args, ctx)
});

// src/lib/mcp/tools/get-product-details.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
var get_product_details_default = defineTool6({
  name: "get_product_details",
  title: "Detalhes do produto",
  description: "Retorna os dados completos de um produto do cat\xE1logo MCI. Somente leitura.",
  inputSchema: { id: z5.string().uuid().describe("UUID do produto MCI") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (args, ctx) => runShared("get_product_details", args, ctx)
});

// src/lib/mcp/tools/search-products.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z6 } from "npm:zod@^3.25.76";
var search_products_default = defineTool7({
  name: "search_products",
  title: "Buscar produtos",
  description: "Busca textual no cat\xE1logo MCI por nome, SKU, marca ou descri\xE7\xE3o.",
  inputSchema: {
    query: z6.string().min(1).describe("Termo de busca"),
    limit: z6.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (args, ctx) => runShared("search_products", args, ctx)
});

// src/lib/mcp/tools/search-quotes.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z7 } from "npm:zod@^3.25.76";
var search_quotes_default = defineTool8({
  name: "search_quotes",
  title: "Buscar or\xE7amentos",
  description: "Busca or\xE7amentos por cliente, status ou intervalo de datas.",
  inputSchema: {
    client_name: z7.string().optional(),
    status: z7.string().optional(),
    from: z7.string().optional().describe("Data inicial ISO (created_at >=)"),
    to: z7.string().optional().describe("Data final ISO (created_at <=)"),
    limit: z7.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (args, ctx) => runShared("search_quotes", args, ctx)
});

// src/lib/mcp/tools/get-pipeline.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_pipeline_default = defineTool9({
  name: "get_pipeline",
  title: "Pipeline comercial",
  description: "Retorna or\xE7amentos agrupados por status para visualiza\xE7\xE3o de pipeline.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (args, ctx) => runShared("get_pipeline", args, ctx)
});

// src/lib/mcp/tools/get-tasks.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z8 } from "npm:zod@^3.25.76";
var get_tasks_default = defineTool10({
  name: "get_tasks",
  title: "Listar tarefas",
  description: "Lista tarefas do usu\xE1rio autenticado, com filtro opcional de status.",
  inputSchema: {
    status: z8.string().optional(),
    limit: z8.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (args, ctx) => runShared("get_tasks", args, ctx)
});

// src/lib/mcp/tools/get-contracts.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z9 } from "npm:zod@^3.25.76";
var get_contracts_default = defineTool11({
  name: "get_contracts",
  title: "Listar contratos",
  description: "Lista contratos gerados e suas solicita\xE7\xF5es de assinatura.",
  inputSchema: {
    status: z9.string().optional(),
    limit: z9.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (args, ctx) => runShared("get_contracts", args, ctx)
});

// src/lib/mcp/tools/get-customer-history.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z10 } from "npm:zod@^3.25.76";
var get_customer_history_default = defineTool12({
  name: "get_customer_history",
  title: "Hist\xF3rico do cliente",
  description: "Retorna or\xE7amentos, contratos e financeiro de um cliente (por id ou nome).",
  inputSchema: {
    client_id: z10.string().uuid().optional(),
    client_name: z10.string().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (args, ctx) => runShared("get_customer_history", args, ctx)
});

// src/lib/mcp/tools/get-dashboard.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_dashboard_default = defineTool13({
  name: "get_dashboard",
  title: "Dashboard comercial",
  description: "Retorna m\xE9tricas resumidas: totais de clientes, or\xE7amentos por status, valor previsto.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (args, ctx) => runShared("get_dashboard", args, ctx)
});

// src/lib/mcp/tools/get-followups.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z11 } from "npm:zod@^3.25.76";
var get_followups_default = defineTool14({
  name: "get_followups",
  title: "Follow-ups pendentes",
  description: "Retorna clientes sem intera\xE7\xE3o recente (default: 30 dias) para follow-up.",
  inputSchema: {
    days_without_contact: z11.number().int().min(1).max(365).default(30),
    limit: z11.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (args, ctx) => runShared("get_followups", args, ctx)
});

// src/lib/mcp/tools/get-sales-metrics.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z12 } from "npm:zod@^3.25.76";
var get_sales_metrics_default = defineTool15({
  name: "get_sales_metrics",
  title: "M\xE9tricas de vendas",
  description: "Retorna m\xE9tricas de vendas (or\xE7amentos aprovados) em um per\xEDodo: receita total, ticket m\xE9dio.",
  inputSchema: {
    from: z12.string().optional().describe("Data inicial ISO"),
    to: z12.string().optional().describe("Data final ISO"),
    days_back: z12.number().int().min(1).max(3650).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (args, ctx) => runShared("get_sales_metrics", args, ctx)
});

// src/lib/mcp/tools/get-top-products.ts
import { defineTool as defineTool16 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z13 } from "npm:zod@^3.25.76";
var get_top_products_default = defineTool16({
  name: "get_top_products",
  title: "Produtos mais vendidos",
  description: "Ranking de produtos mais vendidos considerando apenas or\xE7amentos aprovados. Escolha metric='quantity' para volume ou 'revenue' para faturamento.",
  inputSchema: {
    from: z13.string().optional().describe("Data inicial ISO"),
    to: z13.string().optional().describe("Data final ISO"),
    days_back: z13.number().int().min(1).max(3650).optional(),
    metric: z13.enum(["quantity", "revenue"]).default("revenue"),
    brand: z13.string().optional(),
    limit: z13.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (args, ctx) => runShared("get_top_products", args, ctx)
});

// src/lib/mcp/index.ts
var projectRef = "npqujpfqsnwxowlciyof";
var mcp_default = defineMcp({
  name: "mci-crm-mcp",
  title: "MCI CRM - Copiloto Comercial",
  version: "0.2.0",
  instructions: "Copiloto Comercial do MCI CRM. Use as ferramentas para consultar clientes, produtos, or\xE7amentos, pipeline, contratos, tarefas, follow-ups e m\xE9tricas de vendas do usu\xE1rio autenticado. Nunca invente dados: se uma consulta retornar vazio, informe. Todas as consultas respeitam as permiss\xF5es (RLS) e a carteira comercial do usu\xE1rio.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_clients_default,
    search_clients_default,
    get_products_default,
    get_product_details_default,
    search_products_default,
    list_quotes_default,
    search_quotes_default,
    get_pipeline_default,
    get_tasks_default,
    get_contracts_default,
    get_customer_history_default,
    get_dashboard_default,
    get_followups_default,
    get_sales_metrics_default,
    get_top_products_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
